services:
  gdprsocial:
    build:
      context: ..
      dockerfile: GDPRSocial/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./log:/app/log
      - ./policies:/app/policies

  benchmark:
    build:
      context: ..
      dockerfile: GDPRSocial/Dockerfile
    volumes:
      - ./benchmark/privacy_testsuite/db_snapshots:/app/benchmark/privacy_testsuite/db_snapshots
      - ./policies:/app/policies
      - ./output:/app/output
      - ./benchmark/privacy_testsuite/logs:/app/benchmark/privacy_testsuite/logs
      - ./benchmark/privacy_testsuite/drivers/minitwitter.py:/app/benchmark/privacy_testsuite/drivers/minitwitter.py
      - ./benchmark/privacy_testsuite/tester.py:/app/benchmark/privacy_testsuite/tester.py
      - ./benchmark/privacy_testsuite/prepare_databases.py:/app/benchmark/privacy_testsuite/prepare_databases.py
      - ./instrlib_filter:/app/instrlib
    entrypoint: ["bash", "benchmark/privacy_testsuite/run_benchmark.sh"]
    command:
      - gdpr
      - /opt/whyenf/enfguard
      - --instrlib
      - /app/instrlib
      - --formula
      - /app/policies/minitwit_gdpr.mfotl
      - --sig
      - /app/policies/minitwit_gdpr.sig
      - --output-dir
      - /app/output
